// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: vpn_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VPNService_Connect_FullMethodName             = "/vpnservice.VPNService/Connect"
	VPNService_Disconnect_FullMethodName          = "/vpnservice.VPNService/Disconnect"
	VPNService_GetStats_FullMethodName            = "/vpnservice.VPNService/GetStats"
	VPNService_SetTLSProfile_FullMethodName       = "/vpnservice.VPNService/SetTLSProfile"
	VPNService_RunLeakTest_FullMethodName         = "/vpnservice.VPNService/RunLeakTest"
	VPNService_GetServers_FullMethodName          = "/vpnservice.VPNService/GetServers"
	VPNService_RefreshSubscription_FullMethodName = "/vpnservice.VPNService/RefreshSubscription"
	VPNService_OnStatusChange_FullMethodName      = "/vpnservice.VPNService/OnStatusChange"
	VPNService_StreamStats_FullMethodName         = "/vpnservice.VPNService/StreamStats"
	VPNService_PingServer_FullMethodName          = "/vpnservice.VPNService/PingServer"
)

// VPNServiceClient is the client API for VPNService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VPNServiceClient interface {
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error)
	Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error)
	GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	SetTLSProfile(ctx context.Context, in *TLSProfileRequest, opts ...grpc.CallOption) (*TLSProfileResponse, error)
	RunLeakTest(ctx context.Context, in *LeakTestRequest, opts ...grpc.CallOption) (*LeakTestResponse, error)
	GetServers(ctx context.Context, in *ServersRequest, opts ...grpc.CallOption) (*ServersResponse, error)
	RefreshSubscription(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (*SubscriptionResponse, error)
	OnStatusChange(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StatusEvent], error)
	StreamStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StatsResponse], error)
	PingServer(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type vPNServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVPNServiceClient(cc grpc.ClientConnInterface) VPNServiceClient {
	return &vPNServiceClient{cc}
}

func (c *vPNServiceClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, VPNService_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vPNServiceClient) Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisconnectResponse)
	err := c.cc.Invoke(ctx, VPNService_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vPNServiceClient) GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, VPNService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vPNServiceClient) SetTLSProfile(ctx context.Context, in *TLSProfileRequest, opts ...grpc.CallOption) (*TLSProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TLSProfileResponse)
	err := c.cc.Invoke(ctx, VPNService_SetTLSProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vPNServiceClient) RunLeakTest(ctx context.Context, in *LeakTestRequest, opts ...grpc.CallOption) (*LeakTestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeakTestResponse)
	err := c.cc.Invoke(ctx, VPNService_RunLeakTest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vPNServiceClient) GetServers(ctx context.Context, in *ServersRequest, opts ...grpc.CallOption) (*ServersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServersResponse)
	err := c.cc.Invoke(ctx, VPNService_GetServers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vPNServiceClient) RefreshSubscription(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (*SubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionResponse)
	err := c.cc.Invoke(ctx, VPNService_RefreshSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vPNServiceClient) OnStatusChange(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StatusEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VPNService_ServiceDesc.Streams[0], VPNService_OnStatusChange_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StatusRequest, StatusEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VPNService_OnStatusChangeClient = grpc.ServerStreamingClient[StatusEvent]

func (c *vPNServiceClient) StreamStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StatsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VPNService_ServiceDesc.Streams[1], VPNService_StreamStats_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StatsRequest, StatsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VPNService_StreamStatsClient = grpc.ServerStreamingClient[StatsResponse]

func (c *vPNServiceClient) PingServer(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, VPNService_PingServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VPNServiceServer is the server API for VPNService service.
// All implementations must embed UnimplementedVPNServiceServer
// for forward compatibility.
type VPNServiceServer interface {
	Connect(context.Context, *ConnectRequest) (*ConnectResponse, error)
	Disconnect(context.Context, *DisconnectRequest) (*DisconnectResponse, error)
	GetStats(context.Context, *StatsRequest) (*StatsResponse, error)
	SetTLSProfile(context.Context, *TLSProfileRequest) (*TLSProfileResponse, error)
	RunLeakTest(context.Context, *LeakTestRequest) (*LeakTestResponse, error)
	GetServers(context.Context, *ServersRequest) (*ServersResponse, error)
	RefreshSubscription(context.Context, *SubscriptionRequest) (*SubscriptionResponse, error)
	OnStatusChange(*StatusRequest, grpc.ServerStreamingServer[StatusEvent]) error
	StreamStats(*StatsRequest, grpc.ServerStreamingServer[StatsResponse]) error
	PingServer(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedVPNServiceServer()
}

// UnimplementedVPNServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVPNServiceServer struct{}

func (UnimplementedVPNServiceServer) Connect(context.Context, *ConnectRequest) (*ConnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedVPNServiceServer) Disconnect(context.Context, *DisconnectRequest) (*DisconnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedVPNServiceServer) GetStats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedVPNServiceServer) SetTLSProfile(context.Context, *TLSProfileRequest) (*TLSProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetTLSProfile not implemented")
}
func (UnimplementedVPNServiceServer) RunLeakTest(context.Context, *LeakTestRequest) (*LeakTestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunLeakTest not implemented")
}
func (UnimplementedVPNServiceServer) GetServers(context.Context, *ServersRequest) (*ServersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServers not implemented")
}
func (UnimplementedVPNServiceServer) RefreshSubscription(context.Context, *SubscriptionRequest) (*SubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshSubscription not implemented")
}
func (UnimplementedVPNServiceServer) OnStatusChange(*StatusRequest, grpc.ServerStreamingServer[StatusEvent]) error {
	return status.Error(codes.Unimplemented, "method OnStatusChange not implemented")
}
func (UnimplementedVPNServiceServer) StreamStats(*StatsRequest, grpc.ServerStreamingServer[StatsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamStats not implemented")
}
func (UnimplementedVPNServiceServer) PingServer(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PingServer not implemented")
}
func (UnimplementedVPNServiceServer) mustEmbedUnimplementedVPNServiceServer() {}
func (UnimplementedVPNServiceServer) testEmbeddedByValue()                    {}

// UnsafeVPNServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VPNServiceServer will
// result in compilation errors.
type UnsafeVPNServiceServer interface {
	mustEmbedUnimplementedVPNServiceServer()
}

func RegisterVPNServiceServer(s grpc.ServiceRegistrar, srv VPNServiceServer) {
	// If the following call panics, it indicates UnimplementedVPNServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VPNService_ServiceDesc, srv)
}

func _VPNService_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VPNServiceServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VPNService_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VPNServiceServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VPNService_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VPNServiceServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VPNService_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VPNServiceServer).Disconnect(ctx, req.(*DisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VPNService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VPNServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VPNService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VPNServiceServer).GetStats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VPNService_SetTLSProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TLSProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VPNServiceServer).SetTLSProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VPNService_SetTLSProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VPNServiceServer).SetTLSProfile(ctx, req.(*TLSProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VPNService_RunLeakTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeakTestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VPNServiceServer).RunLeakTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VPNService_RunLeakTest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VPNServiceServer).RunLeakTest(ctx, req.(*LeakTestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VPNService_GetServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VPNServiceServer).GetServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VPNService_GetServers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VPNServiceServer).GetServers(ctx, req.(*ServersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VPNService_RefreshSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VPNServiceServer).RefreshSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VPNService_RefreshSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VPNServiceServer).RefreshSubscription(ctx, req.(*SubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VPNService_OnStatusChange_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VPNServiceServer).OnStatusChange(m, &grpc.GenericServerStream[StatusRequest, StatusEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VPNService_OnStatusChangeServer = grpc.ServerStreamingServer[StatusEvent]

func _VPNService_StreamStats_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StatsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VPNServiceServer).StreamStats(m, &grpc.GenericServerStream[StatsRequest, StatsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VPNService_StreamStatsServer = grpc.ServerStreamingServer[StatsResponse]

func _VPNService_PingServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VPNServiceServer).PingServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VPNService_PingServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VPNServiceServer).PingServer(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VPNService_ServiceDesc is the grpc.ServiceDesc for VPNService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VPNService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vpnservice.VPNService",
	HandlerType: (*VPNServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _VPNService_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _VPNService_Disconnect_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _VPNService_GetStats_Handler,
		},
		{
			MethodName: "SetTLSProfile",
			Handler:    _VPNService_SetTLSProfile_Handler,
		},
		{
			MethodName: "RunLeakTest",
			Handler:    _VPNService_RunLeakTest_Handler,
		},
		{
			MethodName: "GetServers",
			Handler:    _VPNService_GetServers_Handler,
		},
		{
			MethodName: "RefreshSubscription",
			Handler:    _VPNService_RefreshSubscription_Handler,
		},
		{
			MethodName: "PingServer",
			Handler:    _VPNService_PingServer_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OnStatusChange",
			Handler:       _VPNService_OnStatusChange_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamStats",
			Handler:       _VPNService_StreamStats_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "vpn_service.proto",
}
