// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: vpn_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConfigUri      string                 `protobuf:"bytes,1,opt,name=config_uri,json=configUri,proto3" json:"config_uri,omitempty"`                // vless://, trojan://, vmess:// URI
	TlsFingerprint string                 `protobuf:"bytes,2,opt,name=tls_fingerprint,json=tlsFingerprint,proto3" json:"tls_fingerprint,omitempty"` // chrome, firefox, safari, edge, random, auto
	KillSwitch     bool                   `protobuf:"varint,3,opt,name=kill_switch,json=killSwitch,proto3" json:"kill_switch,omitempty"`
	MaskingSni     string                 `protobuf:"bytes,4,opt,name=masking_sni,json=maskingSni,proto3" json:"masking_sni,omitempty"` // override SNI to mask as vk.com, ok.ru, etc.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_vpn_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_vpn_service_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectRequest) GetConfigUri() string {
	if x != nil {
		return x.ConfigUri
	}
	return ""
}

func (x *ConnectRequest) GetTlsFingerprint() string {
	if x != nil {
		return x.TlsFingerprint
	}
	return ""
}

func (x *ConnectRequest) GetKillSwitch() bool {
	if x != nil {
		return x.KillSwitch
	}
	return false
}

func (x *ConnectRequest) GetMaskingSni() string {
	if x != nil {
		return x.MaskingSni
	}
	return ""
}

type ConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ServerIp      string                 `protobuf:"bytes,3,opt,name=server_ip,json=serverIp,proto3" json:"server_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_vpn_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_vpn_service_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConnectResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConnectResponse) GetServerIp() string {
	if x != nil {
		return x.ServerIp
	}
	return ""
}

type DisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectRequest) Reset() {
	*x = DisconnectRequest{}
	mi := &file_vpn_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectRequest) ProtoMessage() {}

func (x *DisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectRequest.ProtoReflect.Descriptor instead.
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return file_vpn_service_proto_rawDescGZIP(), []int{2}
}

type DisconnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectResponse) Reset() {
	*x = DisconnectResponse{}
	mi := &file_vpn_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectResponse) ProtoMessage() {}

func (x *DisconnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectResponse.ProtoReflect.Descriptor instead.
func (*DisconnectResponse) Descriptor() ([]byte, []int) {
	return file_vpn_service_proto_rawDescGZIP(), []int{3}
}

func (x *DisconnectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DisconnectResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_vpn_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_vpn_service_proto_rawDescGZIP(), []int{4}
}

type StatsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UploadBytes    int64                  `protobuf:"varint,1,opt,name=upload_bytes,json=uploadBytes,proto3" json:"upload_bytes,omitempty"`
	DownloadBytes  int64                  `protobuf:"varint,2,opt,name=download_bytes,json=downloadBytes,proto3" json:"download_bytes,omitempty"`
	UploadSpeed    int64                  `protobuf:"varint,3,opt,name=upload_speed,json=uploadSpeed,proto3" json:"upload_speed,omitempty"`       // bytes per second
	DownloadSpeed  int64                  `protobuf:"varint,4,opt,name=download_speed,json=downloadSpeed,proto3" json:"download_speed,omitempty"` // bytes per second
	PingMs         int32                  `protobuf:"varint,5,opt,name=ping_ms,json=pingMs,proto3" json:"ping_ms,omitempty"`
	ConnectedSince int64                  `protobuf:"varint,6,opt,name=connected_since,json=connectedSince,proto3" json:"connected_since,omitempty"` // unix timestamp
	State          string                 `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`                                          // disconnected, connecting, connected, disconnecting
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_vpn_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_vpn_service_proto_rawDescGZIP(), []int{5}
}

func (x *StatsResponse) GetUploadBytes() int64 {
	if x != nil {
		return x.UploadBytes
	}
	return 0
}

func (x *StatsResponse) GetDownloadBytes() int64 {
	if x != nil {
		return x.DownloadBytes
	}
	return 0
}

func (x *StatsResponse) GetUploadSpeed() int64 {
	if x != nil {
		return x.UploadSpeed
	}
	return 0
}

func (x *StatsResponse) GetDownloadSpeed() int64 {
	if x != nil {
		return x.DownloadSpeed
	}
	return 0
}

func (x *StatsResponse) GetPingMs() int32 {
	if x != nil {
		return x.PingMs
	}
	return 0
}

func (x *StatsResponse) GetConnectedSince() int64 {
	if x != nil {
		return x.ConnectedSince
	}
	return 0
}

func (x *StatsResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type TLSProfileRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Profile          string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"` // chrome, firefox, safari, edge, random, auto
	RotationEnabled  bool                   `protobuf:"varint,2,opt,name=rotation_enabled,json=rotationEnabled,proto3" json:"rotation_enabled,omitempty"`
	RotationInterval int32                  `protobuf:"varint,3,opt,name=rotation_interval,json=rotationInterval,proto3" json:"rotation_interval,omitempty"` // seconds
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TLSProfileRequest) Reset() {
	*x = TLSProfileRequest{}
	mi := &file_vpn_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSProfileRequest) ProtoMessage() {}

func (x *TLSProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSProfileRequest.ProtoReflect.Descriptor instead.
func (*TLSProfileRequest) Descriptor() ([]byte, []int) {
	return file_vpn_service_proto_rawDescGZIP(), []int{6}
}

func (x *TLSProfileRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *TLSProfileRequest) GetRotationEnabled() bool {
	if x != nil {
		return x.RotationEnabled
	}
	return false
}

func (x *TLSProfileRequest) GetRotationInterval() int32 {
	if x != nil {
		return x.RotationInterval
	}
	return 0
}

type TLSProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ActiveProfile string                 `protobuf:"bytes,2,opt,name=active_profile,json=activeProfile,proto3" json:"active_profile,omitempty"`
	Ja3Hash       string                 `protobuf:"bytes,3,opt,name=ja3_hash,json=ja3Hash,proto3" json:"ja3_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLSProfileResponse) Reset() {
	*x = TLSProfileResponse{}
	mi := &file_vpn_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSProfileResponse) ProtoMessage() {}

func (x *TLSProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSProfileResponse.ProtoReflect.Descriptor instead.
func (*TLSProfileResponse) Descriptor() ([]byte, []int) {
	return file_vpn_service_proto_rawDescGZIP(), []int{7}
}

func (x *TLSProfileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TLSProfileResponse) GetActiveProfile() string {
	if x != nil {
		return x.ActiveProfile
	}
	return ""
}

func (x *TLSProfileResponse) GetJa3Hash() string {
	if x != nil {
		return x.Ja3Hash
	}
	return ""
}

type LeakTestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeakTestRequest) Reset() {
	*x = LeakTestRequest{}
	mi := &file_vpn_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeakTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeakTestRequest) ProtoMessage() {}

func (x *LeakTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeakTestRequest.ProtoReflect.Descriptor instead.
func (*LeakTestRequest) Descriptor() ([]byte, []int) {
	return file_vpn_service_proto_rawDescGZIP(), []int{8}
}

type LeakTestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VisibleIp     string                 `protobuf:"bytes,1,opt,name=visible_ip,json=visibleIp,proto3" json:"visible_ip,omitempty"`
	RealIp        string                 `protobuf:"bytes,2,opt,name=real_ip,json=realIp,proto3" json:"real_ip,omitempty"`
	IpLeaked      bool                   `protobuf:"varint,3,opt,name=ip_leaked,json=ipLeaked,proto3" json:"ip_leaked,omitempty"`
	DnsServers    []string               `protobuf:"bytes,4,rep,name=dns_servers,json=dnsServers,proto3" json:"dns_servers,omitempty"`
	DnsLeaked     bool                   `protobuf:"varint,5,opt,name=dns_leaked,json=dnsLeaked,proto3" json:"dns_leaked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeakTestResponse) Reset() {
	*x = LeakTestResponse{}
	mi := &file_vpn_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeakTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeakTestResponse) ProtoMessage() {}

func (x *LeakTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeakTestResponse.ProtoReflect.Descriptor instead.
func (*LeakTestResponse) Descriptor() ([]byte, []int) {
	return file_vpn_service_proto_rawDescGZIP(), []int{9}
}

func (x *LeakTestResponse) GetVisibleIp() string {
	if x != nil {
		return x.VisibleIp
	}
	return ""
}

func (x *LeakTestResponse) GetRealIp() string {
	if x != nil {
		return x.RealIp
	}
	return ""
}

func (x *LeakTestResponse) GetIpLeaked() bool {
	if x != nil {
		return x.IpLeaked
	}
	return false
}

func (x *LeakTestResponse) GetDnsServers() []string {
	if x != nil {
		return x.DnsServers
	}
	return nil
}

func (x *LeakTestResponse) GetDnsLeaked() bool {
	if x != nil {
		return x.DnsLeaked
	}
	return false
}

type ServersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServersRequest) Reset() {
	*x = ServersRequest{}
	mi := &file_vpn_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServersRequest) ProtoMessage() {}

func (x *ServersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServersRequest.ProtoReflect.Descriptor instead.
func (*ServersRequest) Descriptor() ([]byte, []int) {
	return file_vpn_service_proto_rawDescGZIP(), []int{10}
}

type ServersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Servers       []*ServerInfo          `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServersResponse) Reset() {
	*x = ServersResponse{}
	mi := &file_vpn_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServersResponse) ProtoMessage() {}

func (x *ServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServersResponse.ProtoReflect.Descriptor instead.
func (*ServersResponse) Descriptor() ([]byte, []int) {
	return file_vpn_service_proto_rawDescGZIP(), []int{11}
}

func (x *ServersResponse) GetServers() []*ServerInfo {
	if x != nil {
		return x.Servers
	}
	return nil
}

type ServerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Protocol      string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	PingMs        int32                  `protobuf:"varint,5,opt,name=ping_ms,json=pingMs,proto3" json:"ping_ms,omitempty"`
	ConfigUri     string                 `protobuf:"bytes,6,opt,name=config_uri,json=configUri,proto3" json:"config_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	mi := &file_vpn_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_vpn_service_proto_rawDescGZIP(), []int{12}
}

func (x *ServerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServerInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ServerInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServerInfo) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ServerInfo) GetPingMs() int32 {
	if x != nil {
		return x.PingMs
	}
	return 0
}

func (x *ServerInfo) GetConfigUri() string {
	if x != nil {
		return x.ConfigUri
	}
	return ""
}

type SubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionRequest) Reset() {
	*x = SubscriptionRequest{}
	mi := &file_vpn_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionRequest) ProtoMessage() {}

func (x *SubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionRequest.ProtoReflect.Descriptor instead.
func (*SubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_vpn_service_proto_rawDescGZIP(), []int{13}
}

func (x *SubscriptionRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type SubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ServersCount  int32                  `protobuf:"varint,2,opt,name=servers_count,json=serversCount,proto3" json:"servers_count,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionResponse) Reset() {
	*x = SubscriptionResponse{}
	mi := &file_vpn_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionResponse) ProtoMessage() {}

func (x *SubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionResponse.ProtoReflect.Descriptor instead.
func (*SubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_vpn_service_proto_rawDescGZIP(), []int{14}
}

func (x *SubscriptionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubscriptionResponse) GetServersCount() int32 {
	if x != nil {
		return x.ServersCount
	}
	return 0
}

func (x *SubscriptionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_vpn_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_vpn_service_proto_rawDescGZIP(), []int{15}
}

func (x *PingRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PingRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PingMs        int32                  `protobuf:"varint,1,opt,name=ping_ms,json=pingMs,proto3" json:"ping_ms,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_vpn_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_vpn_service_proto_rawDescGZIP(), []int{16}
}

func (x *PingResponse) GetPingMs() int32 {
	if x != nil {
		return x.PingMs
	}
	return 0
}

func (x *PingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PingResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_vpn_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_vpn_service_proto_rawDescGZIP(), []int{17}
}

type StatusEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusEvent) Reset() {
	*x = StatusEvent{}
	mi := &file_vpn_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusEvent) ProtoMessage() {}

func (x *StatusEvent) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusEvent.ProtoReflect.Descriptor instead.
func (*StatusEvent) Descriptor() ([]byte, []int) {
	return file_vpn_service_proto_rawDescGZIP(), []int{18}
}

func (x *StatusEvent) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *StatusEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StatusEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_vpn_service_proto protoreflect.FileDescriptor

const file_vpn_service_proto_rawDesc = "" +
	"\n" +
	"\x11vpn_service.proto\x12\n" +
	"vpnservice\"\x9a\x01\n" +
	"\x0eConnectRequest\x12\x1d\n" +
	"\n" +
	"config_uri\x18\x01 \x01(\tR\tconfigUri\x12'\n" +
	"\x0ftls_fingerprint\x18\x02 \x01(\tR\x0etlsFingerprint\x12\x1f\n" +
	"\vkill_switch\x18\x03 \x01(\bR\n" +
	"killSwitch\x12\x1f\n" +
	"\vmasking_sni\x18\x04 \x01(\tR\n" +
	"maskingSni\"b\n" +
	"\x0fConnectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tserver_ip\x18\x03 \x01(\tR\bserverIp\"\x13\n" +
	"\x11DisconnectRequest\"H\n" +
	"\x12DisconnectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x0e\n" +
	"\fStatsRequest\"\xfb\x01\n" +
	"\rStatsResponse\x12!\n" +
	"\fupload_bytes\x18\x01 \x01(\x03R\vuploadBytes\x12%\n" +
	"\x0edownload_bytes\x18\x02 \x01(\x03R\rdownloadBytes\x12!\n" +
	"\fupload_speed\x18\x03 \x01(\x03R\vuploadSpeed\x12%\n" +
	"\x0edownload_speed\x18\x04 \x01(\x03R\rdownloadSpeed\x12\x17\n" +
	"\aping_ms\x18\x05 \x01(\x05R\x06pingMs\x12'\n" +
	"\x0fconnected_since\x18\x06 \x01(\x03R\x0econnectedSince\x12\x14\n" +
	"\x05state\x18\a \x01(\tR\x05state\"\x85\x01\n" +
	"\x11TLSProfileRequest\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\x12)\n" +
	"\x10rotation_enabled\x18\x02 \x01(\bR\x0frotationEnabled\x12+\n" +
	"\x11rotation_interval\x18\x03 \x01(\x05R\x10rotationInterval\"p\n" +
	"\x12TLSProfileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0eactive_profile\x18\x02 \x01(\tR\ractiveProfile\x12\x19\n" +
	"\bja3_hash\x18\x03 \x01(\tR\aja3Hash\"\x11\n" +
	"\x0fLeakTestRequest\"\xa7\x01\n" +
	"\x10LeakTestResponse\x12\x1d\n" +
	"\n" +
	"visible_ip\x18\x01 \x01(\tR\tvisibleIp\x12\x17\n" +
	"\areal_ip\x18\x02 \x01(\tR\x06realIp\x12\x1b\n" +
	"\tip_leaked\x18\x03 \x01(\bR\bipLeaked\x12\x1f\n" +
	"\vdns_servers\x18\x04 \x03(\tR\n" +
	"dnsServers\x12\x1d\n" +
	"\n" +
	"dns_leaked\x18\x05 \x01(\bR\tdnsLeaked\"\x10\n" +
	"\x0eServersRequest\"C\n" +
	"\x0fServersResponse\x120\n" +
	"\aservers\x18\x01 \x03(\v2\x16.vpnservice.ServerInfoR\aservers\"\xa2\x01\n" +
	"\n" +
	"ServerInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12\x17\n" +
	"\aping_ms\x18\x05 \x01(\x05R\x06pingMs\x12\x1d\n" +
	"\n" +
	"config_uri\x18\x06 \x01(\tR\tconfigUri\"'\n" +
	"\x13SubscriptionRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"o\n" +
	"\x14SubscriptionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rservers_count\x18\x02 \x01(\x05R\fserversCount\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\";\n" +
	"\vPingRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\"W\n" +
	"\fPingResponse\x12\x17\n" +
	"\aping_ms\x18\x01 \x01(\x05R\x06pingMs\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x0f\n" +
	"\rStatusRequest\"[\n" +
	"\vStatusEvent\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp2\xe8\x05\n" +
	"\n" +
	"VPNService\x12B\n" +
	"\aConnect\x12\x1a.vpnservice.ConnectRequest\x1a\x1b.vpnservice.ConnectResponse\x12K\n" +
	"\n" +
	"Disconnect\x12\x1d.vpnservice.DisconnectRequest\x1a\x1e.vpnservice.DisconnectResponse\x12?\n" +
	"\bGetStats\x12\x18.vpnservice.StatsRequest\x1a\x19.vpnservice.StatsResponse\x12N\n" +
	"\rSetTLSProfile\x12\x1d.vpnservice.TLSProfileRequest\x1a\x1e.vpnservice.TLSProfileResponse\x12H\n" +
	"\vRunLeakTest\x12\x1b.vpnservice.LeakTestRequest\x1a\x1c.vpnservice.LeakTestResponse\x12E\n" +
	"\n" +
	"GetServers\x12\x1a.vpnservice.ServersRequest\x1a\x1b.vpnservice.ServersResponse\x12X\n" +
	"\x13RefreshSubscription\x12\x1f.vpnservice.SubscriptionRequest\x1a .vpnservice.SubscriptionResponse\x12F\n" +
	"\x0eOnStatusChange\x12\x19.vpnservice.StatusRequest\x1a\x17.vpnservice.StatusEvent0\x01\x12D\n" +
	"\vStreamStats\x12\x18.vpnservice.StatsRequest\x1a\x19.vpnservice.StatsResponse0\x01\x12?\n" +
	"\n" +
	"PingServer\x12\x17.vpnservice.PingRequest\x1a\x18.vpnservice.PingResponseB\x1aZ\x18servc_vpn/core/api/protob\x06proto3"

var (
	file_vpn_service_proto_rawDescOnce sync.Once
	file_vpn_service_proto_rawDescData []byte
)

func file_vpn_service_proto_rawDescGZIP() []byte {
	file_vpn_service_proto_rawDescOnce.Do(func() {
		file_vpn_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vpn_service_proto_rawDesc), len(file_vpn_service_proto_rawDesc)))
	})
	return file_vpn_service_proto_rawDescData
}

var file_vpn_service_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_vpn_service_proto_goTypes = []any{
	(*ConnectRequest)(nil),       // 0: vpnservice.ConnectRequest
	(*ConnectResponse)(nil),      // 1: vpnservice.ConnectResponse
	(*DisconnectRequest)(nil),    // 2: vpnservice.DisconnectRequest
	(*DisconnectResponse)(nil),   // 3: vpnservice.DisconnectResponse
	(*StatsRequest)(nil),         // 4: vpnservice.StatsRequest
	(*StatsResponse)(nil),        // 5: vpnservice.StatsResponse
	(*TLSProfileRequest)(nil),    // 6: vpnservice.TLSProfileRequest
	(*TLSProfileResponse)(nil),   // 7: vpnservice.TLSProfileResponse
	(*LeakTestRequest)(nil),      // 8: vpnservice.LeakTestRequest
	(*LeakTestResponse)(nil),     // 9: vpnservice.LeakTestResponse
	(*ServersRequest)(nil),       // 10: vpnservice.ServersRequest
	(*ServersResponse)(nil),      // 11: vpnservice.ServersResponse
	(*ServerInfo)(nil),           // 12: vpnservice.ServerInfo
	(*SubscriptionRequest)(nil),  // 13: vpnservice.SubscriptionRequest
	(*SubscriptionResponse)(nil), // 14: vpnservice.SubscriptionResponse
	(*PingRequest)(nil),          // 15: vpnservice.PingRequest
	(*PingResponse)(nil),         // 16: vpnservice.PingResponse
	(*StatusRequest)(nil),        // 17: vpnservice.StatusRequest
	(*StatusEvent)(nil),          // 18: vpnservice.StatusEvent
}
var file_vpn_service_proto_depIdxs = []int32{
	12, // 0: vpnservice.ServersResponse.servers:type_name -> vpnservice.ServerInfo
	0,  // 1: vpnservice.VPNService.Connect:input_type -> vpnservice.ConnectRequest
	2,  // 2: vpnservice.VPNService.Disconnect:input_type -> vpnservice.DisconnectRequest
	4,  // 3: vpnservice.VPNService.GetStats:input_type -> vpnservice.StatsRequest
	6,  // 4: vpnservice.VPNService.SetTLSProfile:input_type -> vpnservice.TLSProfileRequest
	8,  // 5: vpnservice.VPNService.RunLeakTest:input_type -> vpnservice.LeakTestRequest
	10, // 6: vpnservice.VPNService.GetServers:input_type -> vpnservice.ServersRequest
	13, // 7: vpnservice.VPNService.RefreshSubscription:input_type -> vpnservice.SubscriptionRequest
	17, // 8: vpnservice.VPNService.OnStatusChange:input_type -> vpnservice.StatusRequest
	4,  // 9: vpnservice.VPNService.StreamStats:input_type -> vpnservice.StatsRequest
	15, // 10: vpnservice.VPNService.PingServer:input_type -> vpnservice.PingRequest
	1,  // 11: vpnservice.VPNService.Connect:output_type -> vpnservice.ConnectResponse
	3,  // 12: vpnservice.VPNService.Disconnect:output_type -> vpnservice.DisconnectResponse
	5,  // 13: vpnservice.VPNService.GetStats:output_type -> vpnservice.StatsResponse
	7,  // 14: vpnservice.VPNService.SetTLSProfile:output_type -> vpnservice.TLSProfileResponse
	9,  // 15: vpnservice.VPNService.RunLeakTest:output_type -> vpnservice.LeakTestResponse
	11, // 16: vpnservice.VPNService.GetServers:output_type -> vpnservice.ServersResponse
	14, // 17: vpnservice.VPNService.RefreshSubscription:output_type -> vpnservice.SubscriptionResponse
	18, // 18: vpnservice.VPNService.OnStatusChange:output_type -> vpnservice.StatusEvent
	5,  // 19: vpnservice.VPNService.StreamStats:output_type -> vpnservice.StatsResponse
	16, // 20: vpnservice.VPNService.PingServer:output_type -> vpnservice.PingResponse
	11, // [11:21] is the sub-list for method output_type
	1,  // [1:11] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_vpn_service_proto_init() }
func file_vpn_service_proto_init() {
	if File_vpn_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vpn_service_proto_rawDesc), len(file_vpn_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vpn_service_proto_goTypes,
		DependencyIndexes: file_vpn_service_proto_depIdxs,
		MessageInfos:      file_vpn_service_proto_msgTypes,
	}.Build()
	File_vpn_service_proto = out.File
	file_vpn_service_proto_goTypes = nil
	file_vpn_service_proto_depIdxs = nil
}
